# WHAT IS PORBABILITY FOR A TEAM AT WORLD CUP TO REACH PLAYOFFS AFTER LOSING FIRST GROUP MATCH?
WITH T1 AS
(SELECT DATE,home_team,away_team,home_score,away_score
FROM results 
WHERE tournament='FIFA WORLD CUP'
UNION 
SELECT DATE,AWAY_team,HOME_team,AWAY_score,HOME_score
FROM results
WHERE tournament='FIFA WORLD CUP')
,T2 AS
(SELECT T1.*, ROW_NUMBER() OVER(PARTITION BY YEAR(DATE),HOME_TEAM ORDER BY DATE, HOME_TEAM) AS RN
FROM T1)
,T3 AS
(SELECT DISTINCT YEAR(DATE) AS YEAR, HOME_TEAM 
FROM T2
WHERE RN=1 AND HOME_SCORE<AWAY_SCORE)

, T4 AS
(SELECT  A.YEAR,home_team, HOME_MATCHES+AWAY_MATCHES AS TOTAL_MATCHES
FROM
(SELECT YEAR(DATE) AS YEAR, HOME_TEAM, COUNT(HOME_TEAM) AS HOME_MATCHES
FROM results R
WHERE tournament='FIFA WORLD CUP'
GROUP BY YEAR,HOME_TEAM) A
LEFT JOIN
(SELECT YEAR(DATE) AS YEAR, AWAY_TEAM, COUNT(AWAY_TEAM) AS AWAY_MATCHES
FROM results R
WHERE tournament='FIFA WORLD CUP'
GROUP BY YEAR,AWAY_TEAM) B
ON A.HOME_TEAM=B.AWAY_TEAM AND A.YEAR=B.YEAR)
,T5 AS
(SELECT T4.YEAR, T4.HOME_TEAM, TOTAL_MATCHES
FROM T4
JOIN T3 ON T4.YEAR=T3.YEAR AND T4.HOME_TEAM=T3.HOME_TEAM
WHERE TOTAL_MATCHES>3)
SELECT 
CONCAT(ROUND((SELECT COUNT(*) FROM T5)/(SELECT COUNT(*) FROM T3)*100,2),' %') AS PROBABILITY